# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 15:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_position', models.CharField(choices=[('w', 'worker'), ('h', 'heler')], default='w', max_length=1)),
                ('name', models.CharField(max_length=250)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('graduation', models.CharField(choices=[('D', '7 pass'), ('C', '10 pass'), ('B', '12 pass'), ('A', 'graduate')], default='D', max_length=1)),
                ('is_married', models.BooleanField(default=True)),
                ('village', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=300)),
                ('ward', models.CharField(max_length=300)),
                ('pincode', models.PositiveIntegerField(default=0)),
                ('has_birth_certi', models.BooleanField(default=False)),
                ('has_marriage_certi', models.BooleanField(default=False)),
                ('has_rashon_certi', models.BooleanField(default=False)),
                ('has_adhaar_certi', models.BooleanField(default=False)),
                ('has_waters_certi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(blank=True, default='', max_length=1000)),
                ('admins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aww.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('center', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aww.Center')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='center',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aww.Center'),
        ),
    ]
