# Generated by Django 2.0.2 on 2018-02-15 12:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(max_length=400)),
                ('address', models.TextField()),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)])),
                ('degree_group', models.CharField(choices=[('AA', 'B.E.'), ('AB', 'B.Com.'), ('BB', 'M.E.'), ('BC', 'Graduate')], default='BC', max_length=2)),
                ('unemployed', models.BooleanField(default=False)),
                ('achievements', models.TextField(blank=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
